#!/usr/bin/env bash

set -x

ghcid \
  --reload=posts \
  --reload=templates \
  --reload=css \
  --reload=site.hs \
  --reload=index.html \
  -c 'stack repl site:exe:site site:test:spec --main-is site:exe:site' \
  -T ':cmd return "let main = Main.main \n :main build \n Spec.main"'
