#!/usr/bin/env bash

trap "pkill -P $$" SIGINT SIGTERM EXIT


webpack-dev-server --config webpack.config.js &

ghcid \
  --reload=posts \
  --reload=templates \
  --reload=css \
  --reload=site.hs \
  --reload=entry.js \
  --reload=index.html \
  -c 'stack repl site:exe:site site:test:spec --main-is site:exe:site' \
  -T ':cmd return "let main = Main.main \n :main build \n Spec.main"'
